---

version: "3.3"

services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: "zeta-user/docker-nginx:latest"
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: "zeta-user/docker-php:latest"
    container_name: php
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: zeta-user/docker-node:latest
    container_name: node
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    networks:
          - appnet

  database:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - nginx_db_data:/var/lib/mysql
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

volumes:
    nginx_db_data: